### ISSUE TITLE
Error in `is_datetime_obj_tz_aware()`

### ISSUE THREAD

**Issue by amonroymz** [MultiX-Amsterdam/structured-data-module#5]
I have encountered this error when running the notebook:

![image](https://github.com/MultiX-Amsterdam/structured-data-module/assets/149786124/72788f9d-cfbe-42e9-945d-f0b939092090)

I'm using Python 3.11.4 and Pandas 2.2.0. Does it work for you?

**Comment by yenchiah** [comment]
I fixed this bug in the new version. Thank you for reporting this!
