### ISSUE TITLE
Suggestion on visualization of data frames

### ISSUE THREAD

**Issue by amonroymz** [MultiX-Amsterdam/structured-data-module#6]
I think it would be a good idea to show the data frames as tables instead of printing them. It would make the notebooks and the website more readable.

Before:
<img width="1236" alt="image" src="https://github.com/MultiX-Amsterdam/structured-data-module/assets/149786124/08832440-e472-4dfd-9fad-58984ab18a31">

After
<img width="1239" alt="image" src="https://github.com/MultiX-Amsterdam/structured-data-module/assets/149786124/31f4875e-f903-4d53-80f6-5765b30800a5">

What do you think? Not sure if this will be shown well after compiling the Jupyter Book.

**Comment by yenchiah** [comment]
I changed many print messages to using the Jupyter notebook printing of pandas tables
